library(lmerTest)
library(lme4)
dat<-read.csv("data/data3by2.csv")
dat$twogroups<-factor(dat$twogroups)
dat$threegroups<-factor(dat$threegroups)
contrasts(dat$twogroups)<-contr.sum(2)
contrasts(dat$threegroups)<-contr.sum(3)

model<-lm(y~threegroups*twogroups,data=dat)
confint(model,level = 0.95)

dat<-read.csv2("data/dat3x2x2_mixed.csv")

dat$wfac<-factor(dat$wfac)
dat$wfac3<-factor(dat$wfac3)
contrasts(dat$wfac)<-contr.sum(2)
contrasts(dat$wfac3)<-contr.sum(3)
dat$bfac<-factor(dat$bfac)
contrasts(dat$bfac)<-contr.sum(2)
dat$cluster<-factor(dat$cluster)

model<-glm(bfac~wfac3*x,data=dat,family = binomial(link = "logit"))
confint(model)
(ss<-summary(model))
ss$coefficients
car::Anova(model,type=3,test="LR")
car::Anova(model,type=3,test="Wald")
glmmodel$model
model$family
model2<-glm(bfac~x,data=dat,family = binomial())
.which.class(model)
mf.anova(model)
q<-mf.summary(model)
class(q)
qq<-car::Anova(model)
class(qq)
model<-lm(y~wfac,data=dat)
qdat<-mf.predict(model2,bars="none")
head(qdat)
names(qdat)
qdat<-mf.predict(model,bars="none")
qdat<-mf.predict(lmer(y~(1|cluster)+x,data=dat),bars="ci")
head(qdat)
