
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(gamlj = list(type = "software", author = "Gallucci, M.", year = 2019, title = "GAMLj: General analyses for linear models", 
    publisher = "[jamovi module]. Retrieved from https://gamlj.github.io/", url = "https://gamlj.github.io/"), effectsize = list(type = "software", 
    author = "Ben-Shachar, Makowski & Lüdecke", year = 2020, title = "Compute and interpret indices of effect size", publisher = "CRAN", 
    url = "https://github.com/easystats/effectsize"))
