
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `gamlj`=list(
        `type`="software", 
        `author`="Gallucci, M.", 
        `year`=2019, 
        `title`="GAMLj: General analyses for linear models", 
        `publisher`="[jamovi module]. Retrieved from https://mcfanda.github.io/gamlj_docs/", 
        `url`="https://mcfanda.github.io/gamlj_docs/"))
