
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `gamlj`=list(
        `type`="software", 
        `author`="Gallucci, M.", 
        `year`=2019, 
        `title`="GAMLj: General analyses for linear models", 
        `publisher`="[jamovi module]. Retrieved from https://gamlj.github.io/", 
        `url`="https://gamlj.github.io/"), 
    `effectsize`=list(
        `type`="software", 
        `author`="Ben-Shachar, Makowski & L\u00FCdecke", 
        `year`=2020, 
        `title`="Compute and interpret indices of effect size", 
        `publisher`="CRAN", 
        `url`="https://github.com/easystats/effectsize"), 
    `parameters`=list(
        `type`="software", 
        `author`="L\u00FCdecke, Ben-Shachar, Patil &  Makowski", 
        `year`=2020, 
        `title`="Extracting, Computing and Exploring the Parameters of Statistical Models using R", 
        `publisher`="CRAN", 
        `url`="https://github.com/easystats/parameters"), 
    `goodness`=list(
        `type`="software", 
        `author`="Gallucci, M.", 
        `year`=2020, 
        `title`="Model goodness of fit in GAMLj", 
        `url`="https://gamlj.github.io/details_goodness.html"), 
    `interactions`=list(
        `type`="software", 
        `title`="interactions: Comprehensive, User-Friendly Toolkit for Probing Interactions. R package version 1.1.0", 
        `author`="Jacob A. Long", 
        `year`=2019, 
        `url`="https://cran.r-project.org/package=interactions"), 
    `margins`=list(
        `type`="software", 
        `title`="Marginal Effects Zoo", 
        `author`="Arel-Bundock V, Greifer N, Heiss A", 
        `year`=2024, 
        `url`="https://marginaleffects.com/"))
