
# This file is automatically generated, you probably don't want to edit this

gamljGlmMixedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljGlmMixedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "glmer",
            .interface = "jamovi",
            dep = NULL,
            factors = NULL,
            covs = NULL,
            model_terms = NULL,
            fixed_intercept = TRUE,
            es = list(
                "expb"),
            expb_ci = FALSE,
            nested_terms = NULL,
            comparison = FALSE,
            nested_intercept = TRUE,
            estimates_ci = TRUE,
            donotrun = FALSE,
            ci_method = "wald",
            boot_r = 1000,
            ci_width = 95,
            contrasts = NULL,
            show_contrastnames = TRUE,
            show_contrastcodes = FALSE,
            plotHAxis = NULL,
            plotSepLines = NULL,
            plotSepPlots = NULL,
            plotRaw = FALSE,
            plotDvScale = FALSE,
            plotOriginalScale = FALSE,
            plotLinesTypes = FALSE,
            plotError = "none",
            emmeans = NULL,
            posthoc = NULL,
            simple_effects = NULL,
            simple_moderators = NULL,
            simple_interactions = FALSE,
            covs_conditioning = "mean_sd",
            ccm_value = 1,
            ccp_value = 25,
            covs_scale_labels = "labels",
            adjust = list(
                "bonf"),
            model_type = "logistic",
            covs_scale = NULL,
            scale_missing = "complete",
            norm_test = FALSE,
            cluster = NULL,
            re = list(
                list()),
            nested_re = list(
                list()),
            re_corr = "all",
            re_modelterms = TRUE,
            re_listing = "none",
            re_lrt = FALSE,
            re_ci = FALSE,
            df_method = "Satterthwaite",
            norm_plot = FALSE,
            qq_plot = FALSE,
            resid_plot = FALSE,
            cluster_boxplot = FALSE,
            cluster_respred = FALSE,
            rand_hist = FALSE, ...) {

            super$initialize(
                package="gamlj",
                name="gamljGlmMixed",
                requiresData=TRUE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="glmer",
                hidden=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                permitted=list(
                    "factor",
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..model_terms <- jmvcore::OptionTerms$new(
                "model_terms",
                model_terms,
                default=NULL)
            private$..fixed_intercept <- jmvcore::OptionBool$new(
                "fixed_intercept",
                fixed_intercept,
                default=TRUE)
            private$..es <- jmvcore::OptionNMXList$new(
                "es",
                es,
                options=list(
                    "expb",
                    "RR",
                    "marginals"),
                default=list(
                    "expb"))
            private$..expb_ci <- jmvcore::OptionBool$new(
                "expb_ci",
                expb_ci,
                default=FALSE)
            private$..nested_terms <- jmvcore::OptionTerms$new(
                "nested_terms",
                nested_terms,
                default=NULL)
            private$..comparison <- jmvcore::OptionBool$new(
                "comparison",
                comparison,
                default=FALSE)
            private$..nested_intercept <- jmvcore::OptionBool$new(
                "nested_intercept",
                nested_intercept,
                default=TRUE)
            private$..estimates_ci <- jmvcore::OptionBool$new(
                "estimates_ci",
                estimates_ci,
                default=TRUE)
            private$..donotrun <- jmvcore::OptionBool$new(
                "donotrun",
                donotrun,
                default=FALSE)
            private$..ci_method <- jmvcore::OptionList$new(
                "ci_method",
                ci_method,
                default="wald",
                options=list(
                    "wald",
                    "profile",
                    "quantile",
                    "bcai"))
            private$..boot_r <- jmvcore::OptionNumber$new(
                "boot_r",
                boot_r,
                min=1,
                default=1000)
            private$..ci_width <- jmvcore::OptionNumber$new(
                "ci_width",
                ci_width,
                min=50,
                max=99.9,
                default=95)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "simple",
                                "deviation",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..show_contrastnames <- jmvcore::OptionBool$new(
                "show_contrastnames",
                show_contrastnames,
                default=TRUE)
            private$..show_contrastcodes <- jmvcore::OptionBool$new(
                "show_contrastcodes",
                show_contrastcodes,
                default=FALSE)
            private$..plotHAxis <- jmvcore::OptionVariable$new(
                "plotHAxis",
                plotHAxis,
                default=NULL)
            private$..plotSepLines <- jmvcore::OptionVariable$new(
                "plotSepLines",
                plotSepLines,
                default=NULL)
            private$..plotSepPlots <- jmvcore::OptionVariables$new(
                "plotSepPlots",
                plotSepPlots,
                default=NULL)
            private$..plotRaw <- jmvcore::OptionBool$new(
                "plotRaw",
                plotRaw,
                default=FALSE)
            private$..plotDvScale <- jmvcore::OptionBool$new(
                "plotDvScale",
                plotDvScale,
                default=FALSE)
            private$..plotOriginalScale <- jmvcore::OptionBool$new(
                "plotOriginalScale",
                plotOriginalScale,
                default=FALSE)
            private$..plotLinesTypes <- jmvcore::OptionBool$new(
                "plotLinesTypes",
                plotLinesTypes,
                default=FALSE)
            private$..plotError <- jmvcore::OptionList$new(
                "plotError",
                plotError,
                options=list(
                    "none",
                    "ci",
                    "se"),
                default="none")
            private$..emmeans <- jmvcore::OptionTerms$new(
                "emmeans",
                emmeans,
                default=NULL)
            private$..posthoc <- jmvcore::OptionTerms$new(
                "posthoc",
                posthoc,
                default=NULL)
            private$..simple_effects <- jmvcore::OptionVariable$new(
                "simple_effects",
                simple_effects,
                default=NULL)
            private$..simple_moderators <- jmvcore::OptionVariables$new(
                "simple_moderators",
                simple_moderators,
                default=NULL)
            private$..simple_interactions <- jmvcore::OptionBool$new(
                "simple_interactions",
                simple_interactions,
                default=FALSE)
            private$..covs_conditioning <- jmvcore::OptionList$new(
                "covs_conditioning",
                covs_conditioning,
                options=list(
                    "mean_sd",
                    "percent"),
                default="mean_sd")
            private$..ccm_value <- jmvcore::OptionNumber$new(
                "ccm_value",
                ccm_value,
                default=1)
            private$..ccp_value <- jmvcore::OptionNumber$new(
                "ccp_value",
                ccp_value,
                default=25,
                min=5,
                max=50)
            private$..covs_scale_labels <- jmvcore::OptionList$new(
                "covs_scale_labels",
                covs_scale_labels,
                options=list(
                    "labels",
                    "values",
                    "values_labels",
                    "uvalues",
                    "uvalues_labels"),
                default="labels")
            private$..adjust <- jmvcore::OptionNMXList$new(
                "adjust",
                adjust,
                options=list(
                    "none",
                    "bonf",
                    "tukey",
                    "holm",
                    "scheffe",
                    "sidak"),
                default=list(
                    "bonf"))
            private$..predicted <- jmvcore::OptionOutput$new(
                "predicted")
            private$..residuals <- jmvcore::OptionOutput$new(
                "residuals")
            private$..model_type <- jmvcore::OptionList$new(
                "model_type",
                model_type,
                options=list(
                    "logistic",
                    "probit",
                    "poisson",
                    "poiover",
                    "nb",
                    "ordinal",
                    "multinomial"),
                default="logistic")
            private$..covs_scale <- jmvcore::OptionArray$new(
                "covs_scale",
                covs_scale,
                items="(covs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "covs_scale",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "centered",
                                "standardized",
                                "clusterbasedcentered",
                                "clustermeans",
                                "clusterbasedstandardized",
                                "none"),
                            default="centered"))))
            private$..scale_missing <- jmvcore::OptionList$new(
                "scale_missing",
                scale_missing,
                options=list(
                    "complete",
                    "colwise"),
                default="complete")
            private$..norm_test <- jmvcore::OptionBool$new(
                "norm_test",
                norm_test,
                default=FALSE)
            private$..cluster <- jmvcore::OptionVariables$new(
                "cluster",
                cluster,
                default=NULL,
                suggested=list(
                    "nominal"))
            private$..re <- jmvcore::OptionArray$new(
                "re",
                re,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "re",
                    NULL))
            private$..nested_re <- jmvcore::OptionArray$new(
                "nested_re",
                nested_re,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "nested_re",
                    NULL))
            private$..re_corr <- jmvcore::OptionList$new(
                "re_corr",
                re_corr,
                options=list(
                    "all",
                    "none",
                    "block"),
                default="all")
            private$..re_modelterms <- jmvcore::OptionBool$new(
                "re_modelterms",
                re_modelterms,
                default=TRUE)
            private$..re_listing <- jmvcore::OptionList$new(
                "re_listing",
                re_listing,
                options=list(
                    "none",
                    "main",
                    "way2",
                    "way3",
                    "all"),
                default="none")
            private$..re_lrt <- jmvcore::OptionBool$new(
                "re_lrt",
                re_lrt,
                default=FALSE)
            private$..re_ci <- jmvcore::OptionBool$new(
                "re_ci",
                re_ci,
                default=FALSE)
            private$..df_method <- jmvcore::OptionList$new(
                "df_method",
                df_method,
                default="Satterthwaite",
                options=list(
                    "Satterthwaite",
                    "Kenward-Roger"))
            private$..norm_plot <- jmvcore::OptionBool$new(
                "norm_plot",
                norm_plot,
                default=FALSE)
            private$..qq_plot <- jmvcore::OptionBool$new(
                "qq_plot",
                qq_plot,
                default=FALSE)
            private$..resid_plot <- jmvcore::OptionBool$new(
                "resid_plot",
                resid_plot,
                default=FALSE)
            private$..cluster_boxplot <- jmvcore::OptionBool$new(
                "cluster_boxplot",
                cluster_boxplot,
                default=FALSE)
            private$..cluster_respred <- jmvcore::OptionBool$new(
                "cluster_respred",
                cluster_respred,
                default=FALSE)
            private$..rand_hist <- jmvcore::OptionBool$new(
                "rand_hist",
                rand_hist,
                default=FALSE)

            self$.addOption(private$...caller)
            self$.addOption(private$...interface)
            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..model_terms)
            self$.addOption(private$..fixed_intercept)
            self$.addOption(private$..es)
            self$.addOption(private$..expb_ci)
            self$.addOption(private$..nested_terms)
            self$.addOption(private$..comparison)
            self$.addOption(private$..nested_intercept)
            self$.addOption(private$..estimates_ci)
            self$.addOption(private$..donotrun)
            self$.addOption(private$..ci_method)
            self$.addOption(private$..boot_r)
            self$.addOption(private$..ci_width)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..show_contrastnames)
            self$.addOption(private$..show_contrastcodes)
            self$.addOption(private$..plotHAxis)
            self$.addOption(private$..plotSepLines)
            self$.addOption(private$..plotSepPlots)
            self$.addOption(private$..plotRaw)
            self$.addOption(private$..plotDvScale)
            self$.addOption(private$..plotOriginalScale)
            self$.addOption(private$..plotLinesTypes)
            self$.addOption(private$..plotError)
            self$.addOption(private$..emmeans)
            self$.addOption(private$..posthoc)
            self$.addOption(private$..simple_effects)
            self$.addOption(private$..simple_moderators)
            self$.addOption(private$..simple_interactions)
            self$.addOption(private$..covs_conditioning)
            self$.addOption(private$..ccm_value)
            self$.addOption(private$..ccp_value)
            self$.addOption(private$..covs_scale_labels)
            self$.addOption(private$..adjust)
            self$.addOption(private$..predicted)
            self$.addOption(private$..residuals)
            self$.addOption(private$..model_type)
            self$.addOption(private$..covs_scale)
            self$.addOption(private$..scale_missing)
            self$.addOption(private$..norm_test)
            self$.addOption(private$..cluster)
            self$.addOption(private$..re)
            self$.addOption(private$..nested_re)
            self$.addOption(private$..re_corr)
            self$.addOption(private$..re_modelterms)
            self$.addOption(private$..re_listing)
            self$.addOption(private$..re_lrt)
            self$.addOption(private$..re_ci)
            self$.addOption(private$..df_method)
            self$.addOption(private$..norm_plot)
            self$.addOption(private$..qq_plot)
            self$.addOption(private$..resid_plot)
            self$.addOption(private$..cluster_boxplot)
            self$.addOption(private$..cluster_respred)
            self$.addOption(private$..rand_hist)
        }),
    active = list(
        .caller = function() private$...caller$value,
        .interface = function() private$...interface$value,
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        model_terms = function() private$..model_terms$value,
        fixed_intercept = function() private$..fixed_intercept$value,
        es = function() private$..es$value,
        expb_ci = function() private$..expb_ci$value,
        nested_terms = function() private$..nested_terms$value,
        comparison = function() private$..comparison$value,
        nested_intercept = function() private$..nested_intercept$value,
        estimates_ci = function() private$..estimates_ci$value,
        donotrun = function() private$..donotrun$value,
        ci_method = function() private$..ci_method$value,
        boot_r = function() private$..boot_r$value,
        ci_width = function() private$..ci_width$value,
        contrasts = function() private$..contrasts$value,
        show_contrastnames = function() private$..show_contrastnames$value,
        show_contrastcodes = function() private$..show_contrastcodes$value,
        plotHAxis = function() private$..plotHAxis$value,
        plotSepLines = function() private$..plotSepLines$value,
        plotSepPlots = function() private$..plotSepPlots$value,
        plotRaw = function() private$..plotRaw$value,
        plotDvScale = function() private$..plotDvScale$value,
        plotOriginalScale = function() private$..plotOriginalScale$value,
        plotLinesTypes = function() private$..plotLinesTypes$value,
        plotError = function() private$..plotError$value,
        emmeans = function() private$..emmeans$value,
        posthoc = function() private$..posthoc$value,
        simple_effects = function() private$..simple_effects$value,
        simple_moderators = function() private$..simple_moderators$value,
        simple_interactions = function() private$..simple_interactions$value,
        covs_conditioning = function() private$..covs_conditioning$value,
        ccm_value = function() private$..ccm_value$value,
        ccp_value = function() private$..ccp_value$value,
        covs_scale_labels = function() private$..covs_scale_labels$value,
        adjust = function() private$..adjust$value,
        predicted = function() private$..predicted$value,
        residuals = function() private$..residuals$value,
        model_type = function() private$..model_type$value,
        covs_scale = function() private$..covs_scale$value,
        scale_missing = function() private$..scale_missing$value,
        norm_test = function() private$..norm_test$value,
        cluster = function() private$..cluster$value,
        re = function() private$..re$value,
        nested_re = function() private$..nested_re$value,
        re_corr = function() private$..re_corr$value,
        re_modelterms = function() private$..re_modelterms$value,
        re_listing = function() private$..re_listing$value,
        re_lrt = function() private$..re_lrt$value,
        re_ci = function() private$..re_ci$value,
        df_method = function() private$..df_method$value,
        norm_plot = function() private$..norm_plot$value,
        qq_plot = function() private$..qq_plot$value,
        resid_plot = function() private$..resid_plot$value,
        cluster_boxplot = function() private$..cluster_boxplot$value,
        cluster_respred = function() private$..cluster_respred$value,
        rand_hist = function() private$..rand_hist$value),
    private = list(
        ...caller = NA,
        ...interface = NA,
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..model_terms = NA,
        ..fixed_intercept = NA,
        ..es = NA,
        ..expb_ci = NA,
        ..nested_terms = NA,
        ..comparison = NA,
        ..nested_intercept = NA,
        ..estimates_ci = NA,
        ..donotrun = NA,
        ..ci_method = NA,
        ..boot_r = NA,
        ..ci_width = NA,
        ..contrasts = NA,
        ..show_contrastnames = NA,
        ..show_contrastcodes = NA,
        ..plotHAxis = NA,
        ..plotSepLines = NA,
        ..plotSepPlots = NA,
        ..plotRaw = NA,
        ..plotDvScale = NA,
        ..plotOriginalScale = NA,
        ..plotLinesTypes = NA,
        ..plotError = NA,
        ..emmeans = NA,
        ..posthoc = NA,
        ..simple_effects = NA,
        ..simple_moderators = NA,
        ..simple_interactions = NA,
        ..covs_conditioning = NA,
        ..ccm_value = NA,
        ..ccp_value = NA,
        ..covs_scale_labels = NA,
        ..adjust = NA,
        ..predicted = NA,
        ..residuals = NA,
        ..model_type = NA,
        ..covs_scale = NA,
        ..scale_missing = NA,
        ..norm_test = NA,
        ..cluster = NA,
        ..re = NA,
        ..nested_re = NA,
        ..re_corr = NA,
        ..re_modelterms = NA,
        ..re_listing = NA,
        ..re_lrt = NA,
        ..re_ci = NA,
        ..df_method = NA,
        ..norm_plot = NA,
        ..qq_plot = NA,
        ..resid_plot = NA,
        ..cluster_boxplot = NA,
        ..cluster_respred = NA,
        ..rand_hist = NA)
)

gamljGlmMixedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljGlmMixedResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        main = function() private$.items[["main"]],
        posthoc = function() private$.items[["posthoc"]],
        simpleEffects = function() private$.items[["simpleEffects"]],
        simpleInteractions = function() private$.items[["simpleInteractions"]],
        emmeans = function() private$.items[["emmeans"]],
        mainPlots = function() private$.items[["mainPlots"]],
        plotnotes = function() private$.items[["plotnotes"]],
        predicted = function() private$.items[["predicted"]],
        residuals = function() private$.items[["residuals"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Generalized Mixed Model")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Model Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Info"),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="")),
                refs="gamlj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    r2 = function() private$.items[["r2"]],
                    fit = function() private$.items[["fit"]],
                    anova = function() private$.items[["anova"]],
                    coefficients = function() private$.items[["coefficients"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]],
                    marginals = function() private$.items[["marginals"]],
                    relativerisk = function() private$.items[["relativerisk"]],
                    random = function() private$.items[["random"]],
                    randomcov = function() private$.items[["randomcov"]],
                    ranova = function() private$.items[["ranova"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="main",
                            title="Model Results")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="r2",
                            title="Model Fit",
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "nested_terms",
                                "fixed_intercept",
                                "comparison",
                                "nested_re",
                                "nested_intercept",
                                "re",
                                "re_corr"),
                            rows=1,
                            columns=list(
                                list(
                                    `name`="model", 
                                    `title`="Model", 
                                    `visible`="(comparison)"),
                                list(
                                    `name`="type", 
                                    `type`="text", 
                                    `title`="Type"),
                                list(
                                    `name`="r2", 
                                    `title`="R\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="test", 
                                    `title`="LRT X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue")),
                            refs="parameters"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="fit",
                            title="Additional Indices",
                            visible=TRUE,
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "fixed_intercept",
                                "comparison",
                                "nested_terms",
                                "nested_re",
                                "nested_intercept",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="info", 
                                    `type`="text", 
                                    `title`="Info"),
                                list(
                                    `name`="value", 
                                    `type`="text", 
                                    `title`="Model Value"),
                                list(
                                    `name`="nested", 
                                    `type`="text", 
                                    `title`="Nested Model", 
                                    `visible`="(comparison)"),
                                list(
                                    `name`="diff", 
                                    `type`="text", 
                                    `title`="\u0394", 
                                    `visible`="(comparison)"),
                                list(
                                    `name`="specs", 
                                    `type`="text", 
                                    `title`="Comment"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="anova",
                            title="Fixed Effects Omnibus Tests",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="test", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter Estimates (Fixed Coefficients)",
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "estimates_ci",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Names", 
                                    `type`="text", 
                                    `visible`="(show_contrastnames)"),
                                list(
                                    `name`="label", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="est.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(estimates_ci)"),
                                list(
                                    `name`="est.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(estimates_ci)"),
                                list(
                                    `name`="expb", 
                                    `type`="number", 
                                    `title`="Exp(B)", 
                                    `visible`="(es:expb)"),
                                list(
                                    `name`="expb.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(es:expb & expb_ci)"),
                                list(
                                    `name`="expb.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(es:expb & expb_ci)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue")),
                            refs="parameters"))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible="(show_contrastcodes)",
                            items="(factors)",
                            clearWith=list(
                                "contrasts"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="Factor: ___key___",
                                columns=list(
                                    list(
                                        `name`="cname", 
                                        `title`="Name", 
                                        `type`="text", 
                                        `visible`="(show_contrastnames)"),
                                    list(
                                        `name`="clab", 
                                        `title`="Contrast", 
                                        `type`="text"),
                                    list(
                                        `name`="bogus", 
                                        `title`="bogus", 
                                        `type`="text", 
                                        `visible`=FALSE)))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="marginals",
                            title="Marginal Effects",
                            visible="(es:marginals)",
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "estimates_ci",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="response", 
                                    `title`="Response", 
                                    `type`="text", 
                                    `combineBelow`=TRUE, 
                                    `visible`="(model_type:multinomial)"),
                                list(
                                    `name`="source", 
                                    `title`="Name", 
                                    `type`="text"),
                                list(
                                    `name`="contrast", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="AME", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="est.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower"),
                                list(
                                    `name`="est.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper"),
                                list(
                                    `name`="test", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="relativerisk",
                            title="Relative risk",
                            visible="(es:RR)",
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "estimates_ci",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Name", 
                                    `type`="text", 
                                    `visible`="(show_contrastnames)"),
                                list(
                                    `name`="label", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="RR", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="est.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(expb_ci | estimates_ci)"),
                                list(
                                    `name`="est.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(expb_ci | estimates_ci)"),
                                list(
                                    `name`="test", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="random",
                            title="Random Components",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr",
                                "re_ci"),
                            columns=list(
                                list(
                                    `name`="groups", 
                                    `title`="Groups", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="name", 
                                    `title`="Name", 
                                    `type`="text"),
                                list(
                                    `name`="std", 
                                    `title`="SD", 
                                    `type`="number"),
                                list(
                                    `name`="var", 
                                    `title`="Variance", 
                                    `type`="number"),
                                list(
                                    `name`="var.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(re_ci)"),
                                list(
                                    `name`="var.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(re_ci)"),
                                list(
                                    `name`="icc", 
                                    `title`="ICC", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="randomcov",
                            title="Random Parameters correlations",
                            visible=FALSE,
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="groups", 
                                    `title`="Groups", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="name", 
                                    `title`="name", 
                                    `type`="text"),
                                list(
                                    `name`="name2", 
                                    `title`="name2", 
                                    `type`="text"),
                                list(
                                    `name`="std", 
                                    `title`="Corr.", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ranova",
                            title="Random Effect LRT",
                            visible="(re_lrt)",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="test", 
                                    `title`="Test", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="npar", 
                                    `title`="N. par", 
                                    `type`="number"),
                                list(
                                    `name`="AIC", 
                                    `title`="AIC", 
                                    `type`="number"),
                                list(
                                    `name`="LRT", 
                                    `title`="LRT", 
                                    `type`="number"),
                                list(
                                    `name`="Df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="Pr(>Chisq)", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="posthoc",
                title="Post Hoc Tests",
                items="(posthoc)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Post Hoc comparison:  ___key___",
                    clearWith=list(
                        "dep",
                        "model_terms",
                        "contrasts",
                        "covs_scale",
                        "fixed_intercept",
                        "ci_width",
                        "ci_method",
                        "boot_r",
                        "df_method",
                        "re",
                        "re_corr",
                        "adjust"),
                    columns=list(
                        list(
                            `name`="response", 
                            `title`="Response", 
                            `type`="text", 
                            `visible`="(model_type:multinomial)", 
                            `combineBelow`=TRUE),
                        list(
                            `name`="estimate", 
                            `title`="Difference", 
                            `type`="number"),
                        list(
                            `name`="se", 
                            `title`="SE", 
                            `type`="number"),
                        list(
                            `name`="est.ci.lower", 
                            `type`="number", 
                            `title`="Lower", 
                            `visible`="(estimates_ci)"),
                        list(
                            `name`="est.ci.upper", 
                            `type`="number", 
                            `title`="Upper", 
                            `visible`="(estimates_ci)"),
                        list(
                            `name`="test", 
                            `title`="z", 
                            `type`="number"),
                        list(
                            `name`="p", 
                            `title`="p", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(adjust:none)"),
                        list(
                            `name`="bonf", 
                            `title`="p<sub>bonferroni</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(adjust:bonf)"),
                        list(
                            `name`="tukey", 
                            `title`="p<sub>tukey</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(adjust:tukey)"),
                        list(
                            `name`="holm", 
                            `title`="p<sub>holm</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(adjust:holm)"),
                        list(
                            `name`="scheffe", 
                            `title`="p<sub>scheffe</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(adjust:scheffe)"),
                        list(
                            `name`="sidak", 
                            `title`="p<sub>sidak</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(adjust:sidak)")))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    anova = function() private$.items[["anova"]],
                    coefficients = function() private$.items[["coefficients"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="simpleEffects",
                            title="Simple Effects")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="anova",
                            title="ANOVA for Simple Effects  of ___key___",
                            visible=FALSE,
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "simple_effects",
                                "simple_moderators",
                                "simple_scale",
                                "ccm_value",
                                "ccp_value",
                                "covs_scale_labels",
                                "covs_conditioning",
                                "df_method"),
                            columns=list(
                                list(
                                    `name`="test", 
                                    `title`="F", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter Estimates for simple effects of ___key___",
                            visible=FALSE,
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "fixed_intercept",
                                "simple_effects",
                                "simple_moderators",
                                "simple_scale",
                                "ccm_value",
                                "ccp_value",
                                "covs_scale_labels",
                                "covs_conditioning",
                                "df_method",
                                "ci_method",
                                "boot_r"),
                            columns=list(
                                list(
                                    `name`="contrast", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="est.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(estimates_ci)"),
                                list(
                                    `name`="est.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(estimates_ci)"),
                                list(
                                    `name`="test", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="simpleInteractions",
                title="Simple Interactions",
                visible="(simple_interactions)",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        anova = function() private$.items[["anova"]],
                        coefficients = function() private$.items[["coefficients"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="Interaction: ___key___",
                                clearWith=list())
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="anova",
                                title="ANOVA",
                                clearWith=list(
                                    "dep",
                                    "model_terms",
                                    "covs_scale",
                                    "fixed_intercept",
                                    "simple_effects",
                                    "simple_moderators",
                                    "simple_scale",
                                    "ccm_value",
                                    "ccp_value",
                                    "covs_scale_labels",
                                    "covs_conditioning",
                                    "df_method"),
                                columns=list(
                                    list(
                                        `name`="effect", 
                                        `title`="Effect", 
                                        `type`="text"),
                                    list(
                                        `name`="test", 
                                        `title`="X\u00B2", 
                                        `type`="number"),
                                    list(
                                        `name`="df1", 
                                        `title`="df1", 
                                        `type`="number"),
                                    list(
                                        `name`="p", 
                                        `title`="p", 
                                        `type`="number", 
                                        `format`="zto,pvalue"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="coefficients",
                                title="Parameter Estimates",
                                clearWith=list(
                                    "dep",
                                    "model_terms",
                                    "covs_scale",
                                    "fixed_intercept",
                                    "simple_effects",
                                    "simple_moderators",
                                    "simple_scale",
                                    "ccm_value",
                                    "ccp_value",
                                    "covs_scale_labels",
                                    "covs_conditioning",
                                    "df_method",
                                    "ci_method",
                                    "boot_r"),
                                columns=list(
                                    list(
                                        `name`="effect", 
                                        `title`="Effect", 
                                        `type`="text"),
                                    list(
                                        `name`="estimate", 
                                        `title`="Estimate", 
                                        `type`="number"),
                                    list(
                                        `name`="se", 
                                        `title`="SE", 
                                        `type`="number"),
                                    list(
                                        `name`="df", 
                                        `title`="df", 
                                        `type`="number"),
                                    list(
                                        `name`="est.ci.lower", 
                                        `title`="Lower", 
                                        `type`="number"),
                                    list(
                                        `name`="est.ci.upper", 
                                        `title`="Upper", 
                                        `type`="number"),
                                    list(
                                        `name`="t", 
                                        `title`="z", 
                                        `type`="number"),
                                    list(
                                        `name`="p", 
                                        `title`="p", 
                                        `type`="number", 
                                        `format`="zto,pvalue"))))}))$new(options=options)))
            self$add(jmvcore::Array$new(
                options=options,
                name="emmeans",
                title="Estimated Marginal Means",
                visible=FALSE,
                items="(emmeans)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Estimate Marginal Means - ___key___",
                    clearWith=list(
                        "ci_width",
                        "ci_method",
                        "boot_r",
                        "emmeans",
                        "df_method",
                        "model_terms"),
                    columns=list(
                        list(
                            `name`="estimate", 
                            `title`="Mean", 
                            `type`="number"),
                        list(
                            `name`="se", 
                            `title`="SE", 
                            `type`="number"),
                        list(
                            `name`="est.ci.lower", 
                            `title`="Lower", 
                            `type`="number"),
                        list(
                            `name`="est.ci.upper", 
                            `title`="Upper", 
                            `type`="number")))))
            self$add(jmvcore::Array$new(
                options=options,
                name="mainPlots",
                title="Results Plots",
                template=jmvcore::Image$new(
                    options=options,
                    title="",
                    renderFun=".mainPlot",
                    width=600,
                    height=400)))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="predicted",
                title="Predicted Vales",
                varTitle="`GZMIXED_PRED_${ dep }`",
                varDescription="Predicted values",
                clearWith=list(
                    "dep",
                    "model_terms",
                    "re")))
            self$add(jmvcore::Output$new(
                options=options,
                name="residuals",
                title="Residuals Vales",
                varTitle="`GZMIXED_RES_${ dep }`",
                varDescription="Residuals values",
                clearWith=list(
                    "dep",
                    "model_terms",
                    "re")))},
        .setModel=function(x) private$..model <- x))

gamljGlmMixedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljGlmMixedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "gamlj",
                name = "gamljGlmMixed",
                version = c(3,0,0),
                options = options,
                results = gamljGlmMixedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Generalized Mixed Model
#'
#' Generalized Mixed  Model
#' 
#'
#' @examples
#' data(schoolexam)
#' gamlj::gamljGlmMixed(
#'        formula = pass ~ 1 + math+( 1|school ),
#'        data = schoolexam)
#'
#' @param data the data as a data frame
#' @param .caller .
#' @param .interface .
#' @param dep a string naming the dependent variable from \code{data}; the
#'   variable must be numeric. Not needed if \code{formula} is used.
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}. Not needed if \code{formula} is used.
#' @param covs a vector of strings naming the covariates from \code{data}. Not
#'   needed if \code{formula} is used.
#' @param model_terms a list of character vectors describing fixed effects
#'   terms. Not needed if \code{formula} is used.
#' @param fixed_intercept \code{TRUE} (default) or \code{FALSE}, estimates
#'   fixed intercept. Not needed if \code{formula} is used.
#' @param es Effect size indices. \code{expb} (default) exponentiates the
#'   coefficients. For dichotomous dependent variables relative risk indices
#'   (RR) can be obtained. \code{marginals} computes the marginal effects.
#' @param expb_ci \code{TRUE} (default) or \code{FALSE} , exp(B) CI in table
#' @param nested_terms a list of character vectors describing effects terms
#'   for nestet. It can be passed as right-hand formula.
#' @param comparison Not present in R
#' @param nested_intercept \code{TRUE} (default) or \code{FALSE}, estimates
#'   fixed intercept. Not needed if \code{formula} is used.
#' @param estimates_ci \code{TRUE} (default) or \code{FALSE} , parameters CI
#'   in table
#' @param donotrun .
#' @param ci_method .
#' @param boot_r a number bootstrap repetitions.
#' @param ci_width a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the plots.
#' @param contrasts a named vector of the form \code{c(var1="type",
#'   var2="type2")} specifying the type of contrast to use, one of
#'   \code{'deviation'}, \code{'simple'}, \code{'dummy'}, \code{'difference'},
#'   \code{'helmert'}, \code{'repeated'} or \code{'polynomial'}. If NULL,
#'   \code{simple} is used. Can also be passed as a list of list of the form
#'   list(list(var="var1",type="type1")).
#' @param show_contrastnames \code{TRUE} or \code{FALSE} (default), shows raw
#'   names of the contrasts variables in tables
#' @param show_contrastcodes \code{TRUE} or \code{FALSE} (default), shows
#'   contrast coefficients tables
#' @param plotHAxis a string naming the variable placed on the horizontal axis
#'   of the plot
#' @param plotSepLines a string naming the variable represented as separate
#'   lines in the plot
#' @param plotSepPlots a list of string naming the variables defining the
#'   levels for multiple plots
#' @param plotRaw \code{TRUE} or \code{FALSE} (default), plot raw data along
#'   the predicted values
#' @param plotDvScale \code{TRUE} or \code{FALSE} (default), set the Y-axis
#'   range equal to the range of the observed values.
#' @param plotOriginalScale \code{TRUE} or \code{FALSE} (default), use
#'   original scale for covariates.
#' @param plotLinesTypes \code{TRUE} or \code{FALSE} (default), use different
#'   linetypes per levels.
#' @param plotError \code{'none'} (default), \code{'ci'}, or \code{'se'}. Use
#'   no error bars, use confidence intervals, or use standard errors on the
#'   plots, respectively.
#' @param emmeans a rhs formula with the terms specifying the marginal means
#'   to estimate (of the form \code{'~x+x:z'})
#' @param posthoc a rhs formula with the terms specifying the table to apply
#'   the comparisons (of the form \code{'~x+x:z'}). The formula is not expanded,
#'   so '\code{x*z}' becomes '\code{x+z' and not '}x+z+x:z\code{'. It can be
#'   passed also as a list of the form '}list("x","z",c("x","z")`'
#' @param simple_effects The variable for which the simple effects (slopes)
#'   are computed
#' @param simple_moderators the variable that provides the levels at which the
#'   simple effects are computed
#' @param simple_interactions should simple Interactions be computed
#' @param covs_conditioning \code{'mean_sd'} (default), \code{'custom'} , or
#'   \code{'percent'}. Use to condition the covariates (if any)
#' @param ccm_value Covariates conditioning mean offset value: how many
#'   st.deviations around the means used to condition simple effects and plots.
#'   Used if \code{covs_conditioning}=\code{'mean_sd'}
#' @param ccp_value Covariates conditioning percentile offset value: number of
#'   percentiles around the median used to condition simple effects and plots.
#'   Used if \code{covs_conditioning}=\code{'percent'}
#' @param covs_scale_labels how the levels of a continuous moderator should
#'   appear in tables and plots: \code{labels}, \code{values} and
#'   \code{values_labels}, \code{ovalues}, `ovalues_labels. The latter two refer
#'   to the variable orginal levels, before scaling.
#' @param adjust one or more of \code{'none'},  \code{'bonf'},\code{'tukey'}
#'   \code{'holm'},\code{'scheffe'}, \code{'tukey'}; provide no,  Bonferroni,
#'   Tukey and Holm Post Hoc corrections respectively.
#' @param model_type Select the generalized linear model:
#'   \code{poisson},\code{logistic},\code{multinomial}, \code{nb},\code{ordinal}
#' @param covs_scale a list of lists specifying the covariates scaling, one of
#'   \code{'centered to the mean'}, \code{'standardized'}, or \code{'none'}.
#'   \code{'none'} leaves the variable as it is
#' @param scale_missing .
#' @param norm_test \code{TRUE} or \code{FALSE} (default), provide a test for
#'   normality of residuals
#' @param cluster a vector of strings naming the clustering variables from
#'   \code{data}
#' @param re a list of lists specifying the models random effects.
#' @param nested_re a list of lists specifying the models random effects.
#' @param re_corr \code{'all'}, \code{'none'} (default), or \code{'block'}.
#'   When random effects are passed as list of length 1, it decides whether the
#'   effects should be correlated,  non correlated. If \code{'re'} is a list of
#'   lists of length > 1, the option is automatially set to \code{'block'}. The
#'   option is ignored if the model is passed using \code{formula}.
#' @param re_modelterms Not in R interface
#' @param re_listing Not in R interface
#' @param re_lrt \code{TRUE} or \code{FALSE} (default), LRT for the random
#'   effects
#' @param re_ci \code{TRUE} or \code{FALSE} (default), confidence intervals
#'   for the random effects
#' @param df_method .
#' @param norm_plot \code{TRUE} or \code{FALSE} (default), provide a histogram
#'   of residuals superimposed by a normal distribution
#' @param qq_plot \code{TRUE} or \code{FALSE} (default), provide a Q-Q plot of
#'   residuals
#' @param resid_plot \code{TRUE} or \code{FALSE} (default), provide a
#'   scatterplot of the residuals against predicted
#' @param cluster_boxplot \code{TRUE} or \code{FALSE} (default), provide a
#'   boxplot of random effects by the first defined clustering variable
#' @param cluster_respred \code{TRUE} or \code{FALSE} (default), residuals vs
#'   predicted by the first defined clustering variable
#' @param rand_hist \code{TRUE} or \code{FALSE} (default), provide histogram
#'   of random Coefficients
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab a property \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$r2} \tab \tab \tab \tab \tab a table of R \cr
#'   \code{results$main$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$anova} \tab \tab \tab \tab \tab a table of omnibus \cr
#'   \code{results$main$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$contrastCodeTables} \tab \tab \tab \tab \tab an array of contrast coefficients tables \cr
#'   \code{results$main$marginals} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$relativerisk} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$random} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$randomcov} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$ranova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$posthoc} \tab \tab \tab \tab \tab an array of post-hoc tables \cr
#'   \code{results$simpleEffects$anova} \tab \tab \tab \tab \tab a table of ANOVA for simple effects \cr
#'   \code{results$simpleEffects$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$simpleInteractions} \tab \tab \tab \tab \tab an array of simple interactions tables \cr
#'   \code{results$emmeans} \tab \tab \tab \tab \tab an array of predicted means tables \cr
#'   \code{results$mainPlots} \tab \tab \tab \tab \tab an array of results plots \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$predicted} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$residuals} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
gamljGlmMixed <- function(
    data,
    .caller = "glmer",
    .interface = "jamovi",
    dep = NULL,
    factors = NULL,
    covs = NULL,
    model_terms = NULL,
    fixed_intercept = TRUE,
    es = list(
                "expb"),
    expb_ci = FALSE,
    nested_terms = NULL,
    comparison = FALSE,
    nested_intercept = TRUE,
    estimates_ci = TRUE,
    donotrun = FALSE,
    ci_method = "wald",
    boot_r = 1000,
    ci_width = 95,
    contrasts = NULL,
    show_contrastnames = TRUE,
    show_contrastcodes = FALSE,
    plotHAxis = NULL,
    plotSepLines = NULL,
    plotSepPlots = NULL,
    plotRaw = FALSE,
    plotDvScale = FALSE,
    plotOriginalScale = FALSE,
    plotLinesTypes = FALSE,
    plotError = "none",
    emmeans = NULL,
    posthoc = NULL,
    simple_effects = NULL,
    simple_moderators = NULL,
    simple_interactions = FALSE,
    covs_conditioning = "mean_sd",
    ccm_value = 1,
    ccp_value = 25,
    covs_scale_labels = "labels",
    adjust = list(
                "bonf"),
    model_type = "logistic",
    covs_scale = NULL,
    scale_missing = "complete",
    norm_test = FALSE,
    cluster = NULL,
    re = list(
                list()),
    nested_re = list(
                list()),
    re_corr = "all",
    re_modelterms = TRUE,
    re_listing = "none",
    re_lrt = FALSE,
    re_ci = FALSE,
    df_method = "Satterthwaite",
    norm_plot = FALSE,
    qq_plot = FALSE,
    resid_plot = FALSE,
    cluster_boxplot = FALSE,
    cluster_respred = FALSE,
    rand_hist = FALSE,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("gamljGlmMixed requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(dep))
            dep <- gamljGlmMixedClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="dep")
        if (missing(factors))
            factors <- gamljGlmMixedClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="factors")
        if (missing(covs))
            covs <- gamljGlmMixedClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="covs")
        if (missing(cluster))
            cluster <- gamljGlmMixedClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="cluster")
        if (missing(re))
            re <- gamljGlmMixedClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="re")
        if (missing(model_terms))
            model_terms <- gamljGlmMixedClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="model_terms")
    }

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(plotHAxis)) plotHAxis <- jmvcore::resolveQuo(jmvcore::enquo(plotHAxis))
    if ( ! missing(plotSepLines)) plotSepLines <- jmvcore::resolveQuo(jmvcore::enquo(plotSepLines))
    if ( ! missing(plotSepPlots)) plotSepPlots <- jmvcore::resolveQuo(jmvcore::enquo(plotSepPlots))
    if ( ! missing(simple_effects)) simple_effects <- jmvcore::resolveQuo(jmvcore::enquo(simple_effects))
    if ( ! missing(simple_moderators)) simple_moderators <- jmvcore::resolveQuo(jmvcore::enquo(simple_moderators))
    if ( ! missing(cluster)) cluster <- jmvcore::resolveQuo(jmvcore::enquo(cluster))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(plotHAxis), plotHAxis, NULL),
            `if`( ! missing(plotSepLines), plotSepLines, NULL),
            `if`( ! missing(plotSepPlots), plotSepPlots, NULL),
            `if`( ! missing(simple_effects), simple_effects, NULL),
            `if`( ! missing(simple_moderators), simple_moderators, NULL),
            `if`( ! missing(cluster), cluster, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    if (inherits(model_terms, "formula")) model_terms <- jmvcore::decomposeFormula(model_terms)
    if (inherits(nested_terms, "formula")) nested_terms <- jmvcore::decomposeFormula(nested_terms)
    if (inherits(emmeans, "formula")) emmeans <- jmvcore::decomposeFormula(emmeans)
    if (inherits(posthoc, "formula")) posthoc <- jmvcore::decomposeFormula(posthoc)

    options <- gamljGlmMixedOptions$new(
        .caller = .caller,
        .interface = .interface,
        dep = dep,
        factors = factors,
        covs = covs,
        model_terms = model_terms,
        fixed_intercept = fixed_intercept,
        es = es,
        expb_ci = expb_ci,
        nested_terms = nested_terms,
        comparison = comparison,
        nested_intercept = nested_intercept,
        estimates_ci = estimates_ci,
        donotrun = donotrun,
        ci_method = ci_method,
        boot_r = boot_r,
        ci_width = ci_width,
        contrasts = contrasts,
        show_contrastnames = show_contrastnames,
        show_contrastcodes = show_contrastcodes,
        plotHAxis = plotHAxis,
        plotSepLines = plotSepLines,
        plotSepPlots = plotSepPlots,
        plotRaw = plotRaw,
        plotDvScale = plotDvScale,
        plotOriginalScale = plotOriginalScale,
        plotLinesTypes = plotLinesTypes,
        plotError = plotError,
        emmeans = emmeans,
        posthoc = posthoc,
        simple_effects = simple_effects,
        simple_moderators = simple_moderators,
        simple_interactions = simple_interactions,
        covs_conditioning = covs_conditioning,
        ccm_value = ccm_value,
        ccp_value = ccp_value,
        covs_scale_labels = covs_scale_labels,
        adjust = adjust,
        model_type = model_type,
        covs_scale = covs_scale,
        scale_missing = scale_missing,
        norm_test = norm_test,
        cluster = cluster,
        re = re,
        nested_re = nested_re,
        re_corr = re_corr,
        re_modelterms = re_modelterms,
        re_listing = re_listing,
        re_lrt = re_lrt,
        re_ci = re_ci,
        df_method = df_method,
        norm_plot = norm_plot,
        qq_plot = qq_plot,
        resid_plot = resid_plot,
        cluster_boxplot = cluster_boxplot,
        cluster_respred = cluster_respred,
        rand_hist = rand_hist)

    analysis <- gamljGlmMixedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

