
# This file is automatically generated, you probably don't want to edit this

gamljMixedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljMixedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factors = NULL,
            covs = NULL,
            modelTerms = NULL,
            fixedIntercept = TRUE,
            showParamsCI = TRUE,
            paramCIWidth = 95,
            contrasts = NULL,
            showRealNames = TRUE,
            showContrastCode = FALSE,
            plotHAxis = NULL,
            plotSepLines = NULL,
            plotSepPlots = NULL,
            plotRaw = FALSE,
            plotDvScale = FALSE,
            plotError = "none",
            ciWidth = 95,
            postHoc = NULL,
            eDesc = FALSE,
            eCovs = FALSE,
            simpleVariable = NULL,
            simpleModerator = NULL,
            simple3way = NULL,
            simpleScale = "mean_sd",
            cvalue = 1,
            percvalue = 25,
            simpleScaleLabels = "labels",
            postHocCorr = list(
                "bonf"),
            scaling = NULL,
            dep_scale = "none",
            cluster = NULL,
            randomTerms = list(
                list()),
            correlatedEffects = "corr",
            reml = TRUE,
            lrtRandomEffects = FALSE,
            ciRE = FALSE,
            plotRandomEffects = FALSE,
            cimethod = "wald",
            dfmethod = "Satterthwaite",
            qq = FALSE,
            normTest = FALSE,
            normPlot = FALSE,
            residPlot = FALSE,
            clusterBoxplot = FALSE,
            randHist = FALSE,
            modelcomparison = FALSE,
            modelid = NULL,
            modeldescription = NULL, ...) {

            super$initialize(
                package="gamlj",
                name="gamljMixed",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..fixedIntercept <- jmvcore::OptionBool$new(
                "fixedIntercept",
                fixedIntercept,
                default=TRUE)
            private$..showParamsCI <- jmvcore::OptionBool$new(
                "showParamsCI",
                showParamsCI,
                default=TRUE)
            private$..paramCIWidth <- jmvcore::OptionNumber$new(
                "paramCIWidth",
                paramCIWidth,
                min=50,
                max=99.9,
                default=95)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "simple",
                                "deviation",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..showRealNames <- jmvcore::OptionBool$new(
                "showRealNames",
                showRealNames,
                default=TRUE)
            private$..showContrastCode <- jmvcore::OptionBool$new(
                "showContrastCode",
                showContrastCode,
                default=FALSE)
            private$..plotHAxis <- jmvcore::OptionVariable$new(
                "plotHAxis",
                plotHAxis,
                default=NULL)
            private$..plotSepLines <- jmvcore::OptionVariable$new(
                "plotSepLines",
                plotSepLines,
                default=NULL)
            private$..plotSepPlots <- jmvcore::OptionVariable$new(
                "plotSepPlots",
                plotSepPlots,
                default=NULL)
            private$..plotRaw <- jmvcore::OptionBool$new(
                "plotRaw",
                plotRaw,
                default=FALSE)
            private$..plotDvScale <- jmvcore::OptionBool$new(
                "plotDvScale",
                plotDvScale,
                default=FALSE)
            private$..plotError <- jmvcore::OptionList$new(
                "plotError",
                plotError,
                options=list(
                    "none",
                    "ci",
                    "se"),
                default="none")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..postHoc <- jmvcore::OptionTerms$new(
                "postHoc",
                postHoc,
                default=NULL)
            private$..eDesc <- jmvcore::OptionBool$new(
                "eDesc",
                eDesc,
                default=FALSE)
            private$..eCovs <- jmvcore::OptionBool$new(
                "eCovs",
                eCovs,
                default=FALSE)
            private$..simpleVariable <- jmvcore::OptionVariable$new(
                "simpleVariable",
                simpleVariable,
                default=NULL)
            private$..simpleModerator <- jmvcore::OptionVariable$new(
                "simpleModerator",
                simpleModerator,
                default=NULL)
            private$..simple3way <- jmvcore::OptionVariable$new(
                "simple3way",
                simple3way,
                default=NULL)
            private$..simpleScale <- jmvcore::OptionList$new(
                "simpleScale",
                simpleScale,
                options=list(
                    "mean_sd",
                    "percent"),
                default="mean_sd")
            private$..cvalue <- jmvcore::OptionNumber$new(
                "cvalue",
                cvalue,
                default=1)
            private$..percvalue <- jmvcore::OptionNumber$new(
                "percvalue",
                percvalue,
                default=25,
                min=5,
                max=50)
            private$..simpleScaleLabels <- jmvcore::OptionList$new(
                "simpleScaleLabels",
                simpleScaleLabels,
                options=list(
                    "labels",
                    "values",
                    "values_labels"),
                default="labels")
            private$..postHocCorr <- jmvcore::OptionNMXList$new(
                "postHocCorr",
                postHocCorr,
                options=list(
                    "none",
                    "bonf",
                    "holm"),
                default=list(
                    "bonf"))
            private$..scaling <- jmvcore::OptionArray$new(
                "scaling",
                scaling,
                items="(covs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "scaling",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "centered",
                                "standardized",
                                "clusterbasedcentered",
                                "clusterbasedstandardized",
                                "log",
                                "none"),
                            default="centered"))))
            private$..dep_scale <- jmvcore::OptionList$new(
                "dep_scale",
                dep_scale,
                options=list(
                    "none",
                    "centered",
                    "standardized",
                    "clusterbasedcentered",
                    "clusterbasedstandardized",
                    "log"),
                default="none")
            private$..cluster <- jmvcore::OptionVariables$new(
                "cluster",
                cluster,
                default=NULL,
                suggested=list(
                    "nominal"))
            private$..randomTerms <- jmvcore::OptionArray$new(
                "randomTerms",
                randomTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "randomTerms",
                    NULL))
            private$..correlatedEffects <- jmvcore::OptionList$new(
                "correlatedEffects",
                correlatedEffects,
                options=list(
                    "corr",
                    "nocorr",
                    "block"),
                default="corr")
            private$..reml <- jmvcore::OptionBool$new(
                "reml",
                reml,
                default=TRUE)
            private$..lrtRandomEffects <- jmvcore::OptionBool$new(
                "lrtRandomEffects",
                lrtRandomEffects,
                default=FALSE)
            private$..ciRE <- jmvcore::OptionBool$new(
                "ciRE",
                ciRE,
                default=FALSE)
            private$..plotRandomEffects <- jmvcore::OptionBool$new(
                "plotRandomEffects",
                plotRandomEffects,
                default=FALSE)
            private$..cimethod <- jmvcore::OptionList$new(
                "cimethod",
                cimethod,
                default="wald",
                options=list(
                    "wald",
                    "profile",
                    "boot"))
            private$..dfmethod <- jmvcore::OptionList$new(
                "dfmethod",
                dfmethod,
                default="Satterthwaite",
                options=list(
                    "Satterthwaite",
                    "Kenward-Roger"))
            private$..qq <- jmvcore::OptionBool$new(
                "qq",
                qq,
                default=FALSE)
            private$..normTest <- jmvcore::OptionBool$new(
                "normTest",
                normTest,
                default=FALSE)
            private$..normPlot <- jmvcore::OptionBool$new(
                "normPlot",
                normPlot,
                default=FALSE)
            private$..residPlot <- jmvcore::OptionBool$new(
                "residPlot",
                residPlot,
                default=FALSE)
            private$..clusterBoxplot <- jmvcore::OptionBool$new(
                "clusterBoxplot",
                clusterBoxplot,
                default=FALSE)
            private$..randHist <- jmvcore::OptionBool$new(
                "randHist",
                randHist,
                default=FALSE)
            private$..predicted <- jmvcore::OptionOutput$new(
                "predicted")
            private$..residuals <- jmvcore::OptionOutput$new(
                "residuals")
            private$..modelcomparison <- jmvcore::OptionBool$new(
                "modelcomparison",
                modelcomparison,
                default=FALSE)
            private$..modelid <- jmvcore::OptionString$new(
                "modelid",
                modelid)
            private$..modeldescription <- jmvcore::OptionString$new(
                "modeldescription",
                modeldescription)

            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..fixedIntercept)
            self$.addOption(private$..showParamsCI)
            self$.addOption(private$..paramCIWidth)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..showRealNames)
            self$.addOption(private$..showContrastCode)
            self$.addOption(private$..plotHAxis)
            self$.addOption(private$..plotSepLines)
            self$.addOption(private$..plotSepPlots)
            self$.addOption(private$..plotRaw)
            self$.addOption(private$..plotDvScale)
            self$.addOption(private$..plotError)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..eDesc)
            self$.addOption(private$..eCovs)
            self$.addOption(private$..simpleVariable)
            self$.addOption(private$..simpleModerator)
            self$.addOption(private$..simple3way)
            self$.addOption(private$..simpleScale)
            self$.addOption(private$..cvalue)
            self$.addOption(private$..percvalue)
            self$.addOption(private$..simpleScaleLabels)
            self$.addOption(private$..postHocCorr)
            self$.addOption(private$..scaling)
            self$.addOption(private$..dep_scale)
            self$.addOption(private$..cluster)
            self$.addOption(private$..randomTerms)
            self$.addOption(private$..correlatedEffects)
            self$.addOption(private$..reml)
            self$.addOption(private$..lrtRandomEffects)
            self$.addOption(private$..ciRE)
            self$.addOption(private$..plotRandomEffects)
            self$.addOption(private$..cimethod)
            self$.addOption(private$..dfmethod)
            self$.addOption(private$..qq)
            self$.addOption(private$..normTest)
            self$.addOption(private$..normPlot)
            self$.addOption(private$..residPlot)
            self$.addOption(private$..clusterBoxplot)
            self$.addOption(private$..randHist)
            self$.addOption(private$..predicted)
            self$.addOption(private$..residuals)
            self$.addOption(private$..modelcomparison)
            self$.addOption(private$..modelid)
            self$.addOption(private$..modeldescription)
        }),
    active = list(
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        modelTerms = function() private$..modelTerms$value,
        fixedIntercept = function() private$..fixedIntercept$value,
        showParamsCI = function() private$..showParamsCI$value,
        paramCIWidth = function() private$..paramCIWidth$value,
        contrasts = function() private$..contrasts$value,
        showRealNames = function() private$..showRealNames$value,
        showContrastCode = function() private$..showContrastCode$value,
        plotHAxis = function() private$..plotHAxis$value,
        plotSepLines = function() private$..plotSepLines$value,
        plotSepPlots = function() private$..plotSepPlots$value,
        plotRaw = function() private$..plotRaw$value,
        plotDvScale = function() private$..plotDvScale$value,
        plotError = function() private$..plotError$value,
        ciWidth = function() private$..ciWidth$value,
        postHoc = function() private$..postHoc$value,
        eDesc = function() private$..eDesc$value,
        eCovs = function() private$..eCovs$value,
        simpleVariable = function() private$..simpleVariable$value,
        simpleModerator = function() private$..simpleModerator$value,
        simple3way = function() private$..simple3way$value,
        simpleScale = function() private$..simpleScale$value,
        cvalue = function() private$..cvalue$value,
        percvalue = function() private$..percvalue$value,
        simpleScaleLabels = function() private$..simpleScaleLabels$value,
        postHocCorr = function() private$..postHocCorr$value,
        scaling = function() private$..scaling$value,
        dep_scale = function() private$..dep_scale$value,
        cluster = function() private$..cluster$value,
        randomTerms = function() private$..randomTerms$value,
        correlatedEffects = function() private$..correlatedEffects$value,
        reml = function() private$..reml$value,
        lrtRandomEffects = function() private$..lrtRandomEffects$value,
        ciRE = function() private$..ciRE$value,
        plotRandomEffects = function() private$..plotRandomEffects$value,
        cimethod = function() private$..cimethod$value,
        dfmethod = function() private$..dfmethod$value,
        qq = function() private$..qq$value,
        normTest = function() private$..normTest$value,
        normPlot = function() private$..normPlot$value,
        residPlot = function() private$..residPlot$value,
        clusterBoxplot = function() private$..clusterBoxplot$value,
        randHist = function() private$..randHist$value,
        predicted = function() private$..predicted$value,
        residuals = function() private$..residuals$value,
        modelcomparison = function() private$..modelcomparison$value,
        modelid = function() private$..modelid$value,
        modeldescription = function() private$..modeldescription$value),
    private = list(
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..modelTerms = NA,
        ..fixedIntercept = NA,
        ..showParamsCI = NA,
        ..paramCIWidth = NA,
        ..contrasts = NA,
        ..showRealNames = NA,
        ..showContrastCode = NA,
        ..plotHAxis = NA,
        ..plotSepLines = NA,
        ..plotSepPlots = NA,
        ..plotRaw = NA,
        ..plotDvScale = NA,
        ..plotError = NA,
        ..ciWidth = NA,
        ..postHoc = NA,
        ..eDesc = NA,
        ..eCovs = NA,
        ..simpleVariable = NA,
        ..simpleModerator = NA,
        ..simple3way = NA,
        ..simpleScale = NA,
        ..cvalue = NA,
        ..percvalue = NA,
        ..simpleScaleLabels = NA,
        ..postHocCorr = NA,
        ..scaling = NA,
        ..dep_scale = NA,
        ..cluster = NA,
        ..randomTerms = NA,
        ..correlatedEffects = NA,
        ..reml = NA,
        ..lrtRandomEffects = NA,
        ..ciRE = NA,
        ..plotRandomEffects = NA,
        ..cimethod = NA,
        ..dfmethod = NA,
        ..qq = NA,
        ..normTest = NA,
        ..normPlot = NA,
        ..residPlot = NA,
        ..clusterBoxplot = NA,
        ..randHist = NA,
        ..predicted = NA,
        ..residuals = NA,
        ..modelcomparison = NA,
        ..modelid = NA,
        ..modeldescription = NA)
)

gamljMixedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljMixedResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        main = function() private$.items[["main"]],
        postHocs = function() private$.items[["postHocs"]],
        simpleEffects = function() private$.items[["simpleEffects"]],
        emeansTables = function() private$.items[["emeansTables"]],
        descPlot = function() private$.items[["descPlot"]],
        descPlots = function() private$.items[["descPlots"]],
        plotnotes = function() private$.items[["plotnotes"]],
        assumptions = function() private$.items[["assumptions"]],
        predicted = function() private$.items[["predicted"]],
        residuals = function() private$.items[["residuals"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixed Model")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Model Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Info"),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`="")),
                clearWith=list(
                    "dep",
                    "dep_scale",
                    "randomTerms",
                    "modelTerms",
                    "fixedIntercept"),
                refs="gamlj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    anova = function() private$.items[["anova"]],
                    fixed = function() private$.items[["fixed"]],
                    random = function() private$.items[["random"]],
                    randomCov = function() private$.items[["randomCov"]],
                    lrtRandomEffectsTable = function() private$.items[["lrtRandomEffectsTable"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="main",
                            title="Model Results",
                            clearWith=list(
                    "dep",
                    "modelTerms",
                    "reml",
                    "contrasts",
                    "scaling",
                    "dep_scale",
                    "randomTerms",
                    "correlatedEffects",
                    "fixedIntercept",
                    "dfmethod"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="anova",
                            title="Fixed Effect Omnibus tests",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "reml",
                                "contrasts",
                                "scaling",
                                "dep_scale",
                                "randomTerms",
                                "correlatedEffects",
                                "fixedIntercept",
                                "dfmethod"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="test", 
                                    `title`="F", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="Num df", 
                                    `type`="number"),
                                list(
                                    `name`="df2", 
                                    `title`="Den df", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="fixed",
                            title="Fixed Effects Parameter Estimates",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "reml",
                                "contrasts",
                                "scaling",
                                "dep_scale",
                                "randomTerms",
                                "correlatedEffects",
                                "fixedIntercept",
                                "paramCIWidth"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Names", 
                                    `type`="text", 
                                    `visible`="(showRealNames)"),
                                list(
                                    `name`="label", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="cilow", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="cihig", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="t", 
                                    `title`="t", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="random",
                            title="Random Components",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "reml",
                                "contrasts",
                                "scaling",
                                "dep_scale",
                                "randomTerms",
                                "correlatedEffects",
                                "fixedIntercept",
                                "randomTerms"),
                            columns=list(
                                list(
                                    `name`="groups", 
                                    `title`="Groups", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="name", 
                                    `title`="Name", 
                                    `type`="text"),
                                list(
                                    `name`="std", 
                                    `title`="SD", 
                                    `type`="number"),
                                list(
                                    `name`="var", 
                                    `title`="Variance", 
                                    `type`="number"),
                                list(
                                    `name`="cilow", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ciRE)"),
                                list(
                                    `name`="cihig", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ciRE)"),
                                list(
                                    `name`="icc", 
                                    `title`="ICC", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="randomCov",
                            title="Random Parameters correlations",
                            visible=FALSE,
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "reml",
                                "contrasts",
                                "scaling",
                                "dep_scale",
                                "randomTerms",
                                "correlatedEffects",
                                "fixedIntercept",
                                "randomTerms"),
                            columns=list(
                                list(
                                    `name`="groups", 
                                    `title`="Groups", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="name1", 
                                    `title`="Param.1", 
                                    `type`="text"),
                                list(
                                    `name`="name2", 
                                    `title`="Param.2", 
                                    `type`="text"),
                                list(
                                    `name`="cov", 
                                    `title`="Corr.", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="lrtRandomEffectsTable",
                            title="Random Effect LRT",
                            visible="(lrtRandomEffects)",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "reml",
                                "contrasts",
                                "scaling",
                                "dep_scale",
                                "randomTerms",
                                "correlatedEffects",
                                "fixedIntercept",
                                "randomTerms"),
                            columns=list(
                                list(
                                    `name`="test", 
                                    `title`="Test", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="npar", 
                                    `title`="N. par", 
                                    `type`="number"),
                                list(
                                    `name`="AIC", 
                                    `title`="AIC", 
                                    `type`="number"),
                                list(
                                    `name`="LRT", 
                                    `title`="LRT", 
                                    `type`="number"),
                                list(
                                    `name`="Df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="Pr(>Chisq)", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible="(showContrastCode)",
                            clearWith=list(
                                "contrasts"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="$key",
                                columns=list(
                                    list(
                                        `name`="rnames", 
                                        `title`="Name", 
                                        `type`="text", 
                                        `visible`="(showRealNames)"),
                                    list(
                                        `name`="clabs", 
                                        `title`="Contrast", 
                                        `type`="text")))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="postHocs",
                title="Post Hoc Tests",
                items="(postHoc)",
                clearWith=list(
                    "dep",
                    "modelTerms",
                    "reml",
                    "contrasts",
                    "scaling",
                    "dep_scale",
                    "randomTerms",
                    "correlatedEffects",
                    "postHocCorr"),
                template=jmvcore::Table$new(
                    options=options,
                    clearWith=list(),
                    title="",
                    columns=list(
                        list(
                            `name`="contrast", 
                            `title`="", 
                            `type`="number", 
                            `visible`=FALSE),
                        list(
                            `name`="estimate", 
                            `title`="Difference", 
                            `type`="number"),
                        list(
                            `name`="se", 
                            `title`="SE", 
                            `type`="number"),
                        list(
                            `name`="test", 
                            `title`="t", 
                            `type`="number"),
                        list(
                            `name`="df", 
                            `title`="df", 
                            `type`="number"),
                        list(
                            `name`="p", 
                            `title`="p", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(postHocCorr:none)"),
                        list(
                            `name`="pbonf", 
                            `title`="p<sub>bonferroni</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(postHocCorr:bonf)"),
                        list(
                            `name`="pholm", 
                            `title`="p<sub>holm</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(postHocCorr:holm)")))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    Anova = function() private$.items[["Anova"]],
                    Params = function() private$.items[["Params"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="simpleEffects",
                            title="Simple Effects",
                            clearWith=list(
                    "dep",
                    "modelTerms",
                    "reml",
                    "contrasts",
                    "scaling",
                    "dep_scale",
                    "randomTerms",
                    "correlatedEffects",
                    "fixedIntercept",
                    "simpleVariable",
                    "simpleModerator",
                    "simple3way",
                    "simpleScale",
                    "cvalue",
                    "percvalue",
                    "simpleScaleLabels"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="Anova",
                            title="Simple Effects ANOVA",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="threeway", 
                                    `title`="", 
                                    `visible`="(simple3way)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="moderator", 
                                    `title`="", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number", 
                                    `visible`=FALSE),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number", 
                                    `visible`=FALSE),
                                list(
                                    `name`="F.ratio", 
                                    `title`="F", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="Num df", 
                                    `type`="number"),
                                list(
                                    `name`="df2", 
                                    `title`="Den df", 
                                    `type`="number"),
                                list(
                                    `name`="p.value", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="Params",
                            title="Parameter Estimates for simple effects",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="threeway", 
                                    `title`=" ", 
                                    `visible`="(simple3way)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="moderator", 
                                    `title`=" ", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="contrast", 
                                    `title`="contrast", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="SE", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="lower.CL", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="upper.CL", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="t.ratio", 
                                    `title`="t", 
                                    `type`="number"),
                                list(
                                    `name`="z.ratio", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p.value", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="emeansTables",
                title="Estimated Marginal Means",
                visible="(eDesc)",
                clearWith=list(
                    "dep",
                    "modelTerms",
                    "reml",
                    "contrasts",
                    "scaling",
                    "dep_scale",
                    "simpleScaleLabels",
                    "randomTerms",
                    "correlatedEffects",
                    "fixedIntercept",
                    "ciWidth"),
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    clearWith=list(),
                    columns=list(
                        list(
                            `name`="emmean", 
                            `title`="Mean", 
                            `type`="number"),
                        list(
                            `name`="SE", 
                            `title`="SE", 
                            `type`="number"),
                        list(
                            `name`="df", 
                            `title`="df", 
                            `type`="number"),
                        list(
                            `name`="lower.CL", 
                            `title`="Lower", 
                            `type`="number"),
                        list(
                            `name`="upper.CL", 
                            `title`="Upper", 
                            `type`="number")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="descPlot",
                title="Effects Plots",
                visible="(plotHAxis)",
                width=500,
                height=300,
                renderFun=".descPlot",
                clearWith=list(
                    "dep",
                    "cluster",
                    "plotHAxis",
                    "plotSepLines",
                    "plotSepPlots",
                    "plotError",
                    "ciWidth",
                    "scaling",
                    "dep_scale",
                    "plotRaw",
                    "plotDvScale",
                    "fixedIntercept",
                    "simpleScale",
                    "simpleScaleLabels",
                    "plotRandomEffects",
                    "randomTerms",
                    "modelTerms",
                    "percvalue",
                    "cvalue")))
            self$add(jmvcore::Array$new(
                options=options,
                name="descPlots",
                title="Results Plots",
                visible="(plotSepPlots)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderFun=".descPlot",
                    width=500,
                    height=300,
                    clearWith=list(
                        "dep",
                        "plotHAxis",
                        "plotSepLines",
                        "plotSepPlots",
                        "plotError",
                        "ciWidth",
                        "scaling",
                        "dep_scale",
                        "modelTerms",
                        "fixedIntercept",
                        "simpleScale",
                        "simpleScaleLabels",
                        "plotDvScale",
                        "plotRandomEffects",
                        "plotRaw",
                        "randomTerms",
                        "percvalue",
                        "cvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                visible=FALSE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    normTest = function() private$.items[["normTest"]],
                    qq = function() private$.items[["qq"]],
                    normPlot = function() private$.items[["normPlot"]],
                    residPlot = function() private$.items[["residPlot"]],
                    clusterBoxplot = function() private$.items[["clusterBoxplot"]],
                    randHist = function() private$.items[["randHist"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="assumptions",
                            title="Assumption Checks")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="normTest",
                            title="Test for Normality of residuals",
                            visible="(normTest)",
                            rows=2,
                            columns=list(
                                list(
                                    `name`="test", 
                                    `title`="Test", 
                                    `type`="number"),
                                list(
                                    `name`="stat", 
                                    `title`="Statistics", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="qq",
                            title="Q-Q Plot",
                            visible="(qq)",
                            width=450,
                            height=400,
                            renderFun=".qqPlot",
                            requiresData=TRUE,
                            clearWith=list(
                                "dep",
                                "modelTerms")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="normPlot",
                            title="Residual histogram",
                            visible="(normPlot)",
                            width=450,
                            height=400,
                            renderFun=".normPlot",
                            requiresData=TRUE,
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "dep_scale")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="residPlot",
                            title="Residual-Predicted Scatterplot",
                            visible="(residPlot)",
                            width=450,
                            height=400,
                            renderFun=".residPlot",
                            requiresData=TRUE,
                            clearWith=list(
                                "dep",
                                "dep_scale",
                                "modelTerms")))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="clusterBoxplot",
                            title="Residuals by cluster boxplot",
                            visible="(clusterBoxplot)",
                            clearWith=list(
                                "dep",
                                "dep_scale",
                                "modelTerms"),
                            template=jmvcore::Image$new(
                                options=options,
                                title="$key",
                                renderFun=".clusterBoxplot",
                                width=450,
                                height=400)))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="randHist",
                            title="Random coefficients histogram",
                            visible="(randHist)",
                            clearWith=list(
                                "dep",
                                "dep_scale",
                                "modelTerms"),
                            template=jmvcore::Image$new(
                                options=options,
                                title="$key",
                                renderFun=".randHist",
                                width=450,
                                height=400)))}))$new(options=options))
            self$add(jmvcore::Output$new(
                options=options,
                name="predicted",
                title="Predicted Vales",
                varTitle="`Mix_PRED_${ dep }`",
                varDescription="Predicted values",
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))
            self$add(jmvcore::Output$new(
                options=options,
                name="residuals",
                title="Residuals Vales",
                varTitle="`Mix_RES_${ dep }`",
                varDescription="Residuals values",
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))},
        .setModel=function(x) private$..model <- x))

gamljMixedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljMixedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "gamlj",
                name = "gamljMixed",
                version = c(2,0,0),
                options = options,
                results = gamljMixedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

