
# This file is automatically generated, you probably don't want to edit this

gamljGzlmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljGzlmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factors = NULL,
            covs = NULL,
            modelTerms = NULL,
            fixedIntercept = TRUE,
            showParamsCI = FALSE,
            showExpbCI = TRUE,
            paramCIWidth = 95,
            contrasts = NULL,
            showRealNames = TRUE,
            showContrastCode = FALSE,
            plotHAxis = NULL,
            plotSepLines = NULL,
            plotSepPlots = NULL,
            plotRaw = FALSE,
            plotDvScale = FALSE,
            plotError = "none",
            ciWidth = 95,
            postHoc = NULL,
            eDesc = FALSE,
            eCovs = FALSE,
            simpleVariable = NULL,
            simpleModerator = NULL,
            simple3way = NULL,
            simpleScale = "mean_sd",
            cvalue = 1,
            percvalue = 25,
            simpleScaleLabels = "labels",
            postHocCorr = list(
                "bonf"),
            scaling = NULL,
            effectSize = list(
                "expb"),
            modelSelection = "linear",
            custom_family = "gaussian",
            custom_link = "identity", ...) {

            super$initialize(
                package="gamlj",
                name="gamljGzlm",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                permitted=list(
                    "numeric",
                    "factor"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..fixedIntercept <- jmvcore::OptionBool$new(
                "fixedIntercept",
                fixedIntercept,
                default=TRUE)
            private$..showParamsCI <- jmvcore::OptionBool$new(
                "showParamsCI",
                showParamsCI,
                default=FALSE)
            private$..showExpbCI <- jmvcore::OptionBool$new(
                "showExpbCI",
                showExpbCI,
                default=TRUE)
            private$..paramCIWidth <- jmvcore::OptionNumber$new(
                "paramCIWidth",
                paramCIWidth,
                min=50,
                max=99.9,
                default=95)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "deviation",
                                "simple",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..showRealNames <- jmvcore::OptionBool$new(
                "showRealNames",
                showRealNames,
                default=TRUE)
            private$..showContrastCode <- jmvcore::OptionBool$new(
                "showContrastCode",
                showContrastCode,
                default=FALSE)
            private$..plotHAxis <- jmvcore::OptionVariable$new(
                "plotHAxis",
                plotHAxis,
                default=NULL)
            private$..plotSepLines <- jmvcore::OptionVariable$new(
                "plotSepLines",
                plotSepLines,
                default=NULL)
            private$..plotSepPlots <- jmvcore::OptionVariable$new(
                "plotSepPlots",
                plotSepPlots,
                default=NULL)
            private$..plotRaw <- jmvcore::OptionBool$new(
                "plotRaw",
                plotRaw,
                default=FALSE)
            private$..plotDvScale <- jmvcore::OptionBool$new(
                "plotDvScale",
                plotDvScale,
                default=FALSE)
            private$..plotError <- jmvcore::OptionList$new(
                "plotError",
                plotError,
                options=list(
                    "none",
                    "ci",
                    "se"),
                default="none")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..postHoc <- jmvcore::OptionTerms$new(
                "postHoc",
                postHoc,
                default=NULL)
            private$..eDesc <- jmvcore::OptionBool$new(
                "eDesc",
                eDesc,
                default=FALSE)
            private$..eCovs <- jmvcore::OptionBool$new(
                "eCovs",
                eCovs,
                default=FALSE)
            private$..simpleVariable <- jmvcore::OptionVariable$new(
                "simpleVariable",
                simpleVariable,
                default=NULL)
            private$..simpleModerator <- jmvcore::OptionVariable$new(
                "simpleModerator",
                simpleModerator,
                default=NULL)
            private$..simple3way <- jmvcore::OptionVariable$new(
                "simple3way",
                simple3way,
                default=NULL)
            private$..simpleScale <- jmvcore::OptionList$new(
                "simpleScale",
                simpleScale,
                options=list(
                    "mean_sd",
                    "percent"),
                default="mean_sd")
            private$..cvalue <- jmvcore::OptionNumber$new(
                "cvalue",
                cvalue,
                default=1)
            private$..percvalue <- jmvcore::OptionNumber$new(
                "percvalue",
                percvalue,
                default=25,
                min=5,
                max=50)
            private$..simpleScaleLabels <- jmvcore::OptionList$new(
                "simpleScaleLabels",
                simpleScaleLabels,
                options=list(
                    "labels",
                    "values",
                    "values_labels"),
                default="labels")
            private$..postHocCorr <- jmvcore::OptionNMXList$new(
                "postHocCorr",
                postHocCorr,
                options=list(
                    "none",
                    "bonf",
                    "holm"),
                default=list(
                    "bonf"))
            private$..scaling <- jmvcore::OptionArray$new(
                "scaling",
                scaling,
                items="(covs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "scaling",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "centered",
                                "standardized",
                                "none"),
                            default="centered"))))
            private$..effectSize <- jmvcore::OptionNMXList$new(
                "effectSize",
                effectSize,
                options=list(
                    "expb",
                    "RR"),
                default=list(
                    "expb"))
            private$..modelSelection <- jmvcore::OptionList$new(
                "modelSelection",
                modelSelection,
                options=list(
                    "linear",
                    "poisson",
                    "poiover",
                    "nb",
                    "logistic",
                    "probit",
                    "custom",
                    "multinomial"),
                default="linear")
            private$..custom_family <- jmvcore::OptionList$new(
                "custom_family",
                custom_family,
                options=list(
                    "gaussian",
                    "binomial",
                    "poisson",
                    "inverse.gaussian",
                    "Gamma"),
                default="gaussian")
            private$..custom_link <- jmvcore::OptionList$new(
                "custom_link",
                custom_link,
                options=list(
                    "identity",
                    "logit",
                    "log",
                    "inverse",
                    "1/mu^2",
                    "sqrt"),
                default="identity")
            private$..predicted <- jmvcore::OptionOutput$new(
                "predicted")
            private$..residuals <- jmvcore::OptionOutput$new(
                "residuals")

            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..fixedIntercept)
            self$.addOption(private$..showParamsCI)
            self$.addOption(private$..showExpbCI)
            self$.addOption(private$..paramCIWidth)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..showRealNames)
            self$.addOption(private$..showContrastCode)
            self$.addOption(private$..plotHAxis)
            self$.addOption(private$..plotSepLines)
            self$.addOption(private$..plotSepPlots)
            self$.addOption(private$..plotRaw)
            self$.addOption(private$..plotDvScale)
            self$.addOption(private$..plotError)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..eDesc)
            self$.addOption(private$..eCovs)
            self$.addOption(private$..simpleVariable)
            self$.addOption(private$..simpleModerator)
            self$.addOption(private$..simple3way)
            self$.addOption(private$..simpleScale)
            self$.addOption(private$..cvalue)
            self$.addOption(private$..percvalue)
            self$.addOption(private$..simpleScaleLabels)
            self$.addOption(private$..postHocCorr)
            self$.addOption(private$..scaling)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..modelSelection)
            self$.addOption(private$..custom_family)
            self$.addOption(private$..custom_link)
            self$.addOption(private$..predicted)
            self$.addOption(private$..residuals)
        }),
    active = list(
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        modelTerms = function() private$..modelTerms$value,
        fixedIntercept = function() private$..fixedIntercept$value,
        showParamsCI = function() private$..showParamsCI$value,
        showExpbCI = function() private$..showExpbCI$value,
        paramCIWidth = function() private$..paramCIWidth$value,
        contrasts = function() private$..contrasts$value,
        showRealNames = function() private$..showRealNames$value,
        showContrastCode = function() private$..showContrastCode$value,
        plotHAxis = function() private$..plotHAxis$value,
        plotSepLines = function() private$..plotSepLines$value,
        plotSepPlots = function() private$..plotSepPlots$value,
        plotRaw = function() private$..plotRaw$value,
        plotDvScale = function() private$..plotDvScale$value,
        plotError = function() private$..plotError$value,
        ciWidth = function() private$..ciWidth$value,
        postHoc = function() private$..postHoc$value,
        eDesc = function() private$..eDesc$value,
        eCovs = function() private$..eCovs$value,
        simpleVariable = function() private$..simpleVariable$value,
        simpleModerator = function() private$..simpleModerator$value,
        simple3way = function() private$..simple3way$value,
        simpleScale = function() private$..simpleScale$value,
        cvalue = function() private$..cvalue$value,
        percvalue = function() private$..percvalue$value,
        simpleScaleLabels = function() private$..simpleScaleLabels$value,
        postHocCorr = function() private$..postHocCorr$value,
        scaling = function() private$..scaling$value,
        effectSize = function() private$..effectSize$value,
        modelSelection = function() private$..modelSelection$value,
        custom_family = function() private$..custom_family$value,
        custom_link = function() private$..custom_link$value,
        predicted = function() private$..predicted$value,
        residuals = function() private$..residuals$value),
    private = list(
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..modelTerms = NA,
        ..fixedIntercept = NA,
        ..showParamsCI = NA,
        ..showExpbCI = NA,
        ..paramCIWidth = NA,
        ..contrasts = NA,
        ..showRealNames = NA,
        ..showContrastCode = NA,
        ..plotHAxis = NA,
        ..plotSepLines = NA,
        ..plotSepPlots = NA,
        ..plotRaw = NA,
        ..plotDvScale = NA,
        ..plotError = NA,
        ..ciWidth = NA,
        ..postHoc = NA,
        ..eDesc = NA,
        ..eCovs = NA,
        ..simpleVariable = NA,
        ..simpleModerator = NA,
        ..simple3way = NA,
        ..simpleScale = NA,
        ..cvalue = NA,
        ..percvalue = NA,
        ..simpleScaleLabels = NA,
        ..postHocCorr = NA,
        ..scaling = NA,
        ..effectSize = NA,
        ..modelSelection = NA,
        ..custom_family = NA,
        ..custom_link = NA,
        ..predicted = NA,
        ..residuals = NA)
)

gamljGzlmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljGzlmResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        main = function() private$.items[["main"]],
        postHocs = function() private$.items[["postHocs"]],
        simpleEffects = function() private$.items[["simpleEffects"]],
        emeansTables = function() private$.items[["emeansTables"]],
        descPlot = function() private$.items[["descPlot"]],
        descPlots = function() private$.items[["descPlots"]],
        predicted = function() private$.items[["predicted"]],
        residuals = function() private$.items[["residuals"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Generalized Linear Model")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Model Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Info"),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`="Value"),
                    list(
                        `name`="comm", 
                        `type`="text", 
                        `title`="Comment")),
                clearWith=list(
                    "dep",
                    "factors",
                    "cov",
                    "modelTerms",
                    "fixedIntercept",
                    "modelSelection",
                    "custom_family",
                    "custom_link"),
                refs="gamlj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    anova = function() private$.items[["anova"]],
                    fixed = function() private$.items[["fixed"]],
                    relativerisk = function() private$.items[["relativerisk"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="main",
                            title="Model Results",
                            clearWith=list(
                    "dep",
                    "modelTerms",
                    "contrasts",
                    "scaling",
                    "fixedIntercept",
                    "modelSelection",
                    "custom_family",
                    "custom_link"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="anova",
                            title="Loglikelihood ratio tests",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "scaling",
                                "fixedIntercept",
                                "effectSize",
                                "modelSelection",
                                "custom_family",
                                "custom_link"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="test", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="fixed",
                            title="Parameter Estimates",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "scaling",
                                "fixedIntercept",
                                "effectSize",
                                "showParamsCI",
                                "showExpbCI",
                                "paramCIWidth",
                                "modelSelection",
                                "custom_family",
                                "custom_link"),
                            columns=list(
                                list(
                                    `name`="dep", 
                                    `title`="Response Contrasts", 
                                    `type`="text", 
                                    `visible`="(modelSelection:multinomial)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="source", 
                                    `title`="Names", 
                                    `type`="text", 
                                    `visible`="(showRealNames)"),
                                list(
                                    `name`="label", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="lower.CL", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="upper.CL", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="expb", 
                                    `title`="exp(B)", 
                                    `type`="number", 
                                    `visible`="(effectSize:expb)"),
                                list(
                                    `name`="lower.ECL", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showExpbCI)"),
                                list(
                                    `name`="upper.ECL", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showExpbCI)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="relativerisk",
                            title="Relative risk",
                            visible="(effectSize:RR)",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "scaling",
                                "fixedIntercept",
                                "effectSize",
                                "ciWidth"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Names", 
                                    `type`="text", 
                                    `visible`="(showRealNames)"),
                                list(
                                    `name`="label", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="RR", 
                                    `type`="number"),
                                list(
                                    `name`="lower.CL", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showExpbCI)"),
                                list(
                                    `name`="upper.CL", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showExpbCI)"))))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible="(showContrastCode)",
                            clearWith=list(
                                "contrasts"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="$key",
                                columns=list(
                                    list(
                                        `name`="rnames", 
                                        `title`="Name", 
                                        `type`="text", 
                                        `visible`="(showRealNames)"),
                                    list(
                                        `name`="clabs", 
                                        `title`="Contrast", 
                                        `type`="text")))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="postHocs",
                title="Post Hoc Tests",
                items="(postHoc)",
                clearWith=list(
                    "dep",
                    "modelTerms",
                    "contrasts",
                    "scaling",
                    "postHocCorr",
                    "modelSelection",
                    "custom_family",
                    "custom_link"),
                template=jmvcore::Table$new(
                    options=options,
                    clearWith=list(),
                    title="",
                    columns=list(
                        list(
                            `name`="response", 
                            `title`="Response Groups", 
                            `type`="text", 
                            `visible`="(modelSelection:multinomial)", 
                            `combineBelow`=TRUE),
                        list(
                            `name`="contrast", 
                            `title`="", 
                            `type`="number", 
                            `visible`=FALSE),
                        list(
                            `name`="estimate", 
                            `title`="Difference", 
                            `type`="number"),
                        list(
                            `name`="se", 
                            `title`="SE", 
                            `type`="number"),
                        list(
                            `name`="test", 
                            `title`="z", 
                            `type`="number"),
                        list(
                            `name`="df", 
                            `title`="df", 
                            `type`="number", 
                            `visible`=FALSE),
                        list(
                            `name`="p", 
                            `title`="p", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(postHocCorr:none)"),
                        list(
                            `name`="pbonf", 
                            `title`="p<sub>bonferroni</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(postHocCorr:bonf)"),
                        list(
                            `name`="pholm", 
                            `title`="p<sub>holm</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(postHocCorr:holm)")))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    Anova = function() private$.items[["Anova"]],
                    Params = function() private$.items[["Params"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="simpleEffects",
                            title="Simple Effects",
                            clearWith=list(
                    "dep",
                    "modelTerms",
                    "contrasts",
                    "scaling",
                    "fixedIntercept",
                    "simpleVariable",
                    "simpleModerator",
                    "simple3way",
                    "simpleScale",
                    "cvalue",
                    "percvalue",
                    "simpleScaleLabels",
                    "modelSelection",
                    "custom_family",
                    "custom_link"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="Anova",
                            title="Simple Effects ANOVA",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="threeway", 
                                    `title`="", 
                                    `visible`="(simple3way)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="moderator", 
                                    `title`="", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="p.value", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="Params",
                            title="Parameter Estimates for simple effects",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="dep", 
                                    `title`="Response Contrasts", 
                                    `type`="text", 
                                    `visible`="(modelSelection:multinomial)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="threeway", 
                                    `title`=" ", 
                                    `visible`="(simple3way)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="moderator", 
                                    `title`=" ", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="contrast", 
                                    `title`="contrast", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="SE", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="lower.CL", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="upper.CL", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showParamsCI)"),
                                list(
                                    `name`="expb", 
                                    `title`="exp(B)", 
                                    `type`="number", 
                                    `visible`="(effectSize:expb)"),
                                list(
                                    `name`="lower.ECL", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(showExpbCI)"),
                                list(
                                    `name`="upper.ECL", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(showExpbCI)"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="t.ratio", 
                                    `title`="t", 
                                    `type`="number"),
                                list(
                                    `name`="z.ratio", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="p.value", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="emeansTables",
                title="Estimated Marginal Means",
                visible="(eDesc)",
                clearWith=list(
                    "dep",
                    "modelTerms",
                    "contrasts",
                    "scaling",
                    "fixedIntercept",
                    "simpleScaleLabels",
                    "ciWidth",
                    "modelSelection",
                    "custom_family",
                    "custom_link"),
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    clearWith=list(),
                    columns=list(
                        list(
                            `name`="emmean", 
                            `title`="Mean", 
                            `type`="number"),
                        list(
                            `name`="SE", 
                            `title`="SE", 
                            `type`="number"),
                        list(
                            `name`="lower.CL", 
                            `title`="Lower", 
                            `type`="number"),
                        list(
                            `name`="upper.CL", 
                            `title`="Upper", 
                            `type`="number")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="descPlot",
                title="Plots",
                visible="(plotHAxis)",
                width=500,
                height=300,
                renderFun=".descPlot",
                clearWith=list(
                    "dep",
                    "plotHAxis",
                    "plotSepLines",
                    "plotSepPlots",
                    "plotError",
                    "ciWidth",
                    "scaling",
                    "plotRaw",
                    "plotDvScale",
                    "fixedIntercept",
                    "simpleScale",
                    "simpleScaleLabels",
                    "modelTerms",
                    "percvalue",
                    "cvalue",
                    "modelSelection",
                    "custom_family",
                    "custom_link")))
            self$add(jmvcore::Array$new(
                options=options,
                name="descPlots",
                title="Results Plots",
                visible="(plotSepPlots)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderFun=".descPlot",
                    width=500,
                    height=300,
                    clearWith=list(
                        "dep",
                        "plotHAxis",
                        "plotSepLines",
                        "plotSepPlots",
                        "plotError",
                        "ciWidth",
                        "scaling",
                        "modelTerms",
                        "fixedIntercept",
                        "simpleScale",
                        "simpleScaleLabels",
                        "plotDvScale",
                        "plotRaw",
                        "modelTerms",
                        "percvalue",
                        "cvalue",
                        "modelSelection",
                        "custom_family",
                        "custom_link"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="predicted",
                title="Predicted Vales",
                varTitle="`GzLM_PRED_${ dep }`",
                varDescription="Predicted values",
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))
            self$add(jmvcore::Output$new(
                options=options,
                name="residuals",
                title="Residuals Vales",
                varTitle="`GzLM_RES_${ dep }`",
                varDescription="Residuals values",
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))},
        .setModel=function(x) private$..model <- x))

gamljGzlmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gamljGzlmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "gamlj",
                name = "gamljGzlm",
                version = c(1,5,2),
                options = options,
                results = gamljGzlmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

